[tool.pyright]
venvPath = "/opt/homebrew/Caskroom/miniconda/base/envs"
venv="ds"

[tool.mypy]
ignore_missing_imports = true
python_executable = "/opt/homebrew/Caskroom/miniconda/base/envs/ds/bin/python"
python_version = "3.10"
# mypy --install-types

[tool.pytest.ini_options]
addopts = "-p no:warnings"
# addopts = "--cov --cov-report html --cov-report term-missing --cov-fail-under 95"

[tool.flake8]
max-line-length = 90

[tool.yapf]
blank_line_before_nested_class_or_def = true

# [tool.pylint]
# max-line-length = 88
# disable = [
#     "C0103", # (invalid-name)
#     "C0114", # (missing-module-docstring)
#     "C0115", # (missing-class-docstring)
#     "C0116", # (missing-function-docstring)
#     "R0903", # (too-few-public-methods)
#     "R0913", # (too-many-arguments)
#     "W0105", # (pointless-string-statement)
# ]

[tool.ruff]
fixable=["ALL"]
# unfixable=["unused-import"]

